# Session 2 : Advanced Constructs in Python & NumPy

Agenda
 - Functions in Python
 - Lambda functions
 - Introdcution to Arrays
 - Array indexing, slicing, and filtering
 - Application of array processing in image processing

## Functions in Python
We have been using Functions in Python. Example `print()` is a function using which we can print any data on the screen. `print()` is an inbuilt Python function.

Similarly we can define our own functions which would take a certain `input` and generate a specific `output`. Functions helps us when we want to use same piece of code in different scenarios. Following examples will help you understand the crux.

In [4]:
# to start with write a function that calculates square of a number
# print the output and the documentation

def square(n):
    # This function calculates square of number
    return n**2

n = int(input())

print(square(n))


34.56


TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

In [9]:
# let us now move on to creating some complex function
# let us create a function to print tables

def table(n, limit=10):
    for i in range(0, limit+1):
        print(n, " X ", i, " = ", n*i)

n = int(input())

table(n)




8
8  X  0  =  0
8  X  1  =  8
8  X  2  =  16
8  X  3  =  24
8  X  4  =  32
8  X  5  =  40
8  X  6  =  48
8  X  7  =  56
8  X  8  =  64
8  X  9  =  72
8  X  10  =  80


In [3]:
# scope of the variable
# a variable defined inside a function cannot be accessed from outside the function
# but a variable defined outside a function can be accessed from inside the function


## Lambda Functions

Lambda function is a small anonymous function in the form

lambda arguments : expression

In [11]:
# lambda function to calculate square of a number

square = lambda x:x*x

square(23)

529

In [12]:
# lambda function to multiply three numbers
multiply = lambda a,b,c:  a*b*c

multiply(2, -1, 3)

-6

## NumPy for Data Science

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python.

Anaconda installation comes with NumPy pre-installed.

In [5]:
# check by importing numpy
import numpy as np

# check the version of numpy
np.__version__

'1.18.5'

## NumPy arrays

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.


<img src = "https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width=400 height=400>

<a href="https://www.oreilly.com/library/view/elegant-scipy/9781491922927/ch01.html">Image Source</a>



## Data Types

Data types supported by NumPy are

 - Integers: `np.int8`, `np.int16`, `np.int32`, `np.int64`, `np.uint8`, …
 - Float: `np.float16`, `np.float32`, `np.float64`, …
 - Complex: `np.complex64 (single precision)`, `np.complex128 (double precision)`, …
 - Boolean: `np.bool8`
 - default type: `np.float64`
 
Complete list of all the data types supported by NumPy can be accessed from the <a href="https://numpy.org/doc/stable/user/basics.types.html">documentation</a>

## Array Indexing, Slicing and Filtering

[start:end:step]

In [9]:
# load the data from patient_data.csv
data = np.loadtxt(fname='patient_data.csv', delimiter=',', dtype=np.int8)
print(data)

[[0 0 1 ... 3 0 0]
 [0 1 2 ... 1 0 1]
 [0 1 1 ... 2 1 1]
 ...
 [0 1 1 ... 1 1 1]
 [0 0 0 ... 0 2 0]
 [0 0 1 ... 1 1 0]]


In [10]:
# print dtype and shape of the dataset
print(data.dtype)
print(data.shape)      #(60,40) data of 60 patients for 40 days 

int8
(60, 40)


In [14]:
# let us take a look at how we can refer to elements in arrays using index
# first element in the array is
print("first element", data[0,0])
print("first row", data[0])

first element 0


In [15]:
# suppose we want data for only first 4 patients
print("first for rows", data[:4]) #data[0:4, 0:7]


first for rows [[ 0  0  1  3  1  2  4  7  8  3  3  3 10  5  7  4  7  7 12 18  6 13 11 11
   7  7  4  6  8  8  4  4  5  7  3  4  2  3  0  0]
 [ 0  1  2  1  2  1  3  2  2  6 10 11  5  9  4  4  7 16  8  6 18  4 12  5
  12  7 11  5 11  3  3  5  4  4  5  5  1  1  0  1]
 [ 0  1  1  3  3  2  6  2  5  9  5  7  4  5  4 15  5 11  9 10 19 14 12 17
   7 12 11  7  4  2 10  5  4  2  2  3  2  2  1  1]
 [ 0  0  2  0  4  2  2  1  6  7 10  7  9 13  8  8 15 10 10  7 17  4  4  7
   6 15  6  4  9 11  3  5  6  3  3  4  2  3  2  1]]


In [21]:
# data of all the patients for first week
dataFirstWeek = data[:, 0:7]
print("first for rows", dataFirstWeek)

first for rows [[0 0 1 3 1 2 4]
 [0 1 2 1 2 1 3]
 [0 1 1 3 3 2 6]
 [0 0 2 0 4 2 2]
 [0 1 1 3 3 1 3]
 [0 0 1 2 2 4 2]
 [0 0 2 2 4 2 2]
 [0 0 1 2 3 1 2]
 [0 0 0 3 1 5 6]
 [0 1 1 2 1 3 5]
 [0 1 0 0 4 3 3]
 [0 1 0 0 3 4 2]
 [0 0 2 1 4 3 6]
 [0 0 0 0 1 3 1]
 [0 1 2 1 1 1 4]
 [0 1 1 0 1 2 4]
 [0 0 0 0 2 3 6]
 [0 0 0 1 2 1 4]
 [0 0 2 1 2 5 4]
 [0 1 2 0 1 4 3]
 [0 1 1 3 1 4 4]
 [0 0 2 3 2 3 2]
 [0 0 0 3 4 5 1]
 [0 1 1 1 1 3 3]
 [0 1 1 1 2 3 5]
 [0 0 2 1 3 3 2]
 [0 0 1 2 4 2 2]
 [0 0 1 1 1 5 1]
 [0 0 2 2 3 4 6]
 [0 0 0 1 4 4 6]
 [0 1 1 0 3 2 4]
 [0 0 2 3 3 4 5]
 [0 1 2 2 2 3 6]
 [0 0 2 1 3 5 6]
 [0 0 1 2 4 1 5]
 [0 0 0 3 1 3 6]
 [0 1 2 2 2 5 5]
 [0 1 1 2 3 1 5]
 [0 1 0 3 2 4 1]
 [0 1 1 3 1 1 5]
 [0 0 0 2 2 1 3]
 [0 0 1 3 3 1 2]
 [0 1 1 3 4 5 2]
 [0 0 1 3 1 4 3]
 [0 1 1 3 3 4 4]
 [0 1 2 2 4 3 1]
 [0 0 2 3 4 5 4]
 [0 1 1 3 1 4 6]
 [0 0 1 3 2 5 1]
 [0 0 1 2 3 4 5]
 [0 1 2 1 1 3 5]
 [0 1 2 2 3 5 2]
 [0 0 0 2 4 4 5]
 [0 0 2 1 1 4 4]
 [0 1 2 1 1 4 5]
 [0 0 1 3 2 3 6]
 [0 1 1 2 2 5 1]
 [0 1 1 1 4 1 6]

In [25]:
# filtering is used to get specific values from an array
# suppose we want only the readings above 10 for all the patients
data > 10 # gives array of array that contains the boolean result of the given condition
data[data > 10]

array([3, 4, 3, 3, 3, 6, 4, 3, 3, 3, 4, 4, 3, 3, 5, 6, 3, 5, 4, 3, 3, 3,
       4, 4, 3, 6, 3, 4, 4, 3, 6, 4, 5, 4, 4, 3, 3, 4, 4, 3, 3, 3, 4, 5,
       3, 3, 3, 5, 3, 3, 4, 5, 3, 4, 6, 4, 4, 6, 3, 4, 3, 3, 4, 5, 3, 6,
       3, 5, 6, 4, 5, 3, 3, 6, 5, 5, 3, 5, 3, 4, 3, 5, 3, 3, 3, 3, 4, 5,
       3, 4, 3, 3, 3, 4, 4, 4, 3, 3, 4, 5, 4, 3, 4, 6, 3, 5, 3, 4, 5, 3,
       5, 3, 5, 4, 4, 5, 4, 4, 4, 5, 3, 3, 6, 5, 4, 6, 4, 5, 6, 3, 5],
      dtype=int8)

## Real life application of NumPy in Image Processing


<img src = "https://datacarpentry.org/image-processing/fig/02-chair-layers-rgb.png" height = 400 width=400>

<img src="sunflower.jpg" width=256 heigth=256>

In [33]:
# import pillow library for loading image as numpy array
#Any image file is 3D array, length and width depends on the resolutiuon of the array
from PIL import Image


im = np.array(Image.open('sunflower.jpeg'))
print(im[0:10,0:10,0])

[[8 7 6 5 4 5 5 6 4 5]
 [7 6 5 5 4 5 6 6 4 4]
 [6 6 6 5 5 5 5 5 3 4]
 [6 6 6 6 5 5 4 3 3 3]
 [6 6 6 6 5 4 4 3 2 3]
 [3 5 5 5 5 5 5 5 2 3]
 [4 4 6 6 5 4 5 5 2 3]
 [8 7 5 6 4 3 3 3 2 3]
 [7 6 5 5 4 3 3 3 1 2]
 [7 6 5 3 4 3 4 3 2 3]]


In [32]:
# shape of the array, image
im.shape

(856, 1280, 3)

In [40]:
# compress the image
im_compress = im.copy()
im_compress = im_compress[::2,::2]
Image.fromarray(im_compress).save('compress_sunflower.jpg')

In [43]:
# crop an image
im_crop = im.copy()
im_crop = im_crop[0:800, 200:1024]
Image.fromarray(im_crop).save('crop_sunflower.jpg')


In [44]:
# rotate image, np.rot90
im_rot = im.copy()
im_rot= np.rot90(im_rot)
Image.fromarray(im_rot).save('rotate_sunflower.jpg')

In [49]:
# extract red color image
im_red = im.copy()
im_red[:,:,(1,2)] = 0

Image.fromarray(im_red).save('redlayer_sunflower.jpg')

im_blue = im.copy()
im_blue[:,:,(0,1)] = 0
Image.fromarray(im_blue).save('bluelayer_sunflower.jpg')


im_green = im.copy()
im_green[:,:,(0,2)] = 0
Image.fromarray(im_green).save('greenlayer_sunflower.jpg')

In [51]:
# grescale image
weights = [0.2989, 0.5870, 0.1140]
im_gs = im.copy()
im_gs = np.dot(im_gs, weights)
im_gs.shape
Image.fromarray(im_gs).convert('RGB').save('gs_sunflower.jpg')

In [60]:
#List comprehension 
all_numbers = [112, 321, 222, 432, 578, 1002, 327,884]

#square of all numbers 
squares = [x**2 for x in all_numbers]
squares
#square of all even numbers
squares_even = [x**2 for x in all_numbers if x%2==0]
squares_even

#square if an even number cube if an odd
new_list = [x**2 if x%2==0 else x**3 for x in all_numbers]
new_list

[12544, 33076161, 49284, 186624, 334084, 1004004, 34965783, 781456]

In [62]:
#Dictionary Comprehension 
# dictionary comprehension example
square_dict = {num: num*num for num in range(1, 11)}
print(square_dict)


#item price in dollars
old_price = {'milk': 1.02, 'coffee': 2.5, 'bread': 2.5}
s
dollar_to_pound = 0.76
new_price = {item: value*dollar_to_pound for (item, value) in old_price.items()}
print(new_price)


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}
{'milk': 0.7752, 'coffee': 1.9, 'bread': 1.9}
